schema_version = "1.0.0"

# Manifest for Blender extension

id = "TopoFit"
version = "1.63.0"
name = "TopoFit"
tagline = "Landmark-guided geodesic topology fitting and deformation."
maintainer = "Lee Butler"
# Supported types: "add-on", "theme"
type = "add-on"

# Optional link to documentation, support, source files, etc
# website = "https://extensions.blender.org/add-ons/my-example-package/"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Modeling", "Mesh", "3D View"]

blender_version_min = "5.0.0"
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
